language: node_js
node_js:
- '0.10'
script: npm run browser-test
env:
  global:
  - secure: 0W+LU2bxEnEFBkidlGQTDVY1rFjA6r521Ha+1Zq491w3vooMG4hs1v9vT4xD96KaYhs5rfQbsBzEAshGdxTC5pIFNM0RLJJXIp9xgYsm5bsMYr5rRbzIE8oIiqNUPWtd3ZDwEqtMRal0e0t+qlLJVT2L0VoQWiODIwZP9oSZg0w=
  - secure: rvFa/cvPPD9YFW/lvdf/qkU3iGQC/7eJTjOgk/1aCXErWaYvOsdRbgeO6DkwkzWjWcTWWX4BPPDELsNjm8mqcEQGylR/xrK2GOVS92MHZzZSn+woOOn1TOC+yeBaEothKcpA05pmvGf9JbDjWVTbgVJUQw7hcRy/Xv+ezXGOxi4=
